### ISSUE TITLE
Provide the source code

### ISSUE THREAD

**Issue by code-affinity** [project-curiosity/jackboxlauncher#1]
This is GitHub. Why not provide the source code?

**Comment by project-curiosity** [comment]
Sorry, the original reason I uploaded it on github was because I wanted to quickly upload the exe but google drive was taking it down. Then I intended on improving the project to my liking and uploading both the source code and compiled exe. I finished the update but I never got around to uploading it. Now the source code and the compiled project are available.

**Comment by code-affinity** [comment]
That is great, thank you!  I'll be trying it out this weekend.
